version: 0.0
os: linux
files:
  - source: /
    destination: /data/deploy
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: verify_service.sh
      timeout: 300
      runas: root
